fix tracing of openai v1.92.0 (#757)
they moved some things out of beta so our type checking broke.

```
    def __init__(self, chat: Any):
        super().__init__(chat)
    
        import openai
    
>       if type(chat.completions) == openai.resources.beta.chat.completions.AsyncCompletions:
E       AttributeError: module 'openai.resources.beta' has no attribute 'chat'
```

https://github.com/openai/openai-python/releases/tag/v1.92.0